[package]
name = "pup"
description = "Upload images in markdown file to github pic repo and replace the local path with the returned URL"
version = "0.1.0"
edition = "2021"
authors = ["SteveLauC <stevelauc@outlook.com>"]
readme = "README.md"
licence = "GPLv2"
categories = ["command-line-utilities"]
repository = "https://github.com/SteveLauC/pup"


[dependencies]
anyhow = "1.0.56"
base64 = "0.13.0"
clap = {version = "3.1.8", features = ["cargo"]}
colored = "2.0.0"
json = "0.12.4"
rayon = "1.5.2"
regex = "1.5.5"
reqwest = {version = "0.11.10", features = ["blocking"]}
serde = "1.0.136"
serde_json = "1.0.79"
toml = "0.5.8"

[profile.release]
strip = true